// Stock symbols to track - S&P 500 + Major European equities

export interface SymbolInfo {
  symbol: string;
  name: string;
  exchange: string;
  currency: string;
  region: 'US' | 'EU';
}

// S&P 500 stocks (comprehensive list)
export const US_SYMBOLS: SymbolInfo[] = [
  // Technology
  { symbol: 'AAPL', name: 'Apple Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'META', name: 'Meta Platforms Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'TSLA', name: 'Tesla Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ORCL', name: 'Oracle Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CRM', name: 'Salesforce Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ACN', name: 'Accenture plc', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ADBE', name: 'Adobe Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'TXN', name: 'Texas Instruments', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'IBM', name: 'IBM Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'INTU', name: 'Intuit Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'INTC', name: 'Intel Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AMAT', name: 'Applied Materials', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'MU', name: 'Micron Technology', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'LRCX', name: 'Lam Research', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ADI', name: 'Analog Devices', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'KLAC', name: 'KLA Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'PANW', name: 'Palo Alto Networks', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'MRVL', name: 'Marvell Technology', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ON', name: 'ON Semiconductor', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'DELL', name: 'Dell Technologies', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HPQ', name: 'HP Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CTSH', name: 'Cognizant Technology', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  
  // Financial Services
  { symbol: 'BRK.B', name: 'Berkshire Hathaway B', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'V', name: 'Visa Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MA', name: 'Mastercard Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BAC', name: 'Bank of America', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'WFC', name: 'Wells Fargo & Co.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'GS', name: 'Goldman Sachs Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MS', name: 'Morgan Stanley', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BLK', name: 'BlackRock Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'C', name: 'Citigroup Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SCHW', name: 'Charles Schwab', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AXP', name: 'American Express', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CB', name: 'Chubb Limited', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MMC', name: 'Marsh & McLennan', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PGR', name: 'Progressive Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CME', name: 'CME Group Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AON', name: 'Aon plc', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'USB', name: 'U.S. Bancorp', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PNC', name: 'PNC Financial Services', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'TFC', name: 'Truist Financial', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AIG', name: 'American International Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MET', name: 'MetLife Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PRU', name: 'Prudential Financial', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PYPL', name: 'PayPal Holdings', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'COF', name: 'Capital One Financial', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ALL', name: 'Allstate Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'TRV', name: 'Travelers Companies', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AFL', name: 'Aflac Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  
  // Healthcare
  { symbol: 'UNH', name: 'UnitedHealth Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MRK', name: 'Merck & Co.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PFE', name: 'Pfizer Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ABT', name: 'Abbott Laboratories', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DHR', name: 'Danaher Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AMGN', name: 'Amgen Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'GILD', name: 'Gilead Sciences', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CVS', name: 'CVS Health Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MDT', name: 'Medtronic plc', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ELV', name: 'Elevance Health', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'SYK', name: 'Stryker Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BSX', name: 'Boston Scientific', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BDX', name: 'Becton Dickinson', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CI', name: 'Cigna Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HCA', name: 'HCA Healthcare', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MCK', name: 'McKesson Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EW', name: 'Edwards Lifesciences', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HUM', name: 'Humana Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'A', name: 'Agilent Technologies', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'IQV', name: 'IQVIA Holdings', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BIIB', name: 'Biogen Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  
  // Consumer Discretionary
  { symbol: 'HD', name: 'Home Depot Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MCD', name: "McDonald's Corp.", exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'NKE', name: 'Nike Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SBUX', name: 'Starbucks Corp.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'LOW', name: "Lowe's Companies", exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'TJX', name: 'TJX Companies', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BKNG', name: 'Booking Holdings', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'F', name: 'Ford Motor Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'GM', name: 'General Motors', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MAR', name: 'Marriott International', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ORLY', name: "O'Reilly Automotive", exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'AZO', name: 'AutoZone Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ROST', name: 'Ross Stores Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'DHI', name: 'D.R. Horton', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'LEN', name: 'Lennar Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'YUM', name: 'Yum! Brands', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HLT', name: 'Hilton Worldwide', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EBAY', name: 'eBay Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'DG', name: 'Dollar General', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'BBY', name: 'Best Buy Co.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'LVS', name: 'Las Vegas Sands', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ULTA', name: 'Ulta Beauty', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'APTV', name: 'Aptiv PLC', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'POOL', name: 'Pool Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'GPC', name: 'Genuine Parts Co.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  
  // Consumer Staples
  { symbol: 'PG', name: 'Procter & Gamble', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'KO', name: 'Coca-Cola Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'COST', name: 'Costco Wholesale', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'WMT', name: 'Walmart Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PM', name: 'Philip Morris International', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MO', name: 'Altria Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MDLZ', name: 'Mondelez International', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CL', name: 'Colgate-Palmolive', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'TGT', name: 'Target Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ADM', name: 'Archer-Daniels-Midland', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SYY', name: 'Sysco Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'KMB', name: 'Kimberly-Clark', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'GIS', name: 'General Mills', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'STZ', name: 'Constellation Brands', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'KR', name: 'Kroger Co.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HSY', name: 'Hershey Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'KHC', name: 'Kraft Heinz Co.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'EL', name: 'Estee Lauder', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'K', name: 'Kellanova', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CHD', name: 'Church & Dwight', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CLX', name: 'Clorox Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CAG', name: 'Conagra Brands', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MKC', name: 'McCormick & Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SJM', name: 'J.M. Smucker', exchange: 'NYSE', currency: 'USD', region: 'US' },
  
  // Industrials
  { symbol: 'CAT', name: 'Caterpillar Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'GE', name: 'GE Aerospace', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'RTX', name: 'RTX Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HON', name: 'Honeywell International', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'UNP', name: 'Union Pacific', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'UPS', name: 'United Parcel Service', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BA', name: 'Boeing Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DE', name: 'Deere & Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'LMT', name: 'Lockheed Martin', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ADP', name: 'Automatic Data Processing', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ETN', name: 'Eaton Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'WM', name: 'Waste Management', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ITW', name: 'Illinois Tool Works', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CSX', name: 'CSX Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'NOC', name: 'Northrop Grumman', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'GD', name: 'General Dynamics', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MMM', name: '3M Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EMR', name: 'Emerson Electric', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'FDX', name: 'FedEx Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'NSC', name: 'Norfolk Southern', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PH', name: 'Parker-Hannifin', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CTAS', name: 'Cintas Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'TT', name: 'Trane Technologies', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CARR', name: 'Carrier Global', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'OTIS', name: 'Otis Worldwide', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'JCI', name: 'Johnson Controls', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ROK', name: 'Rockwell Automation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'FAST', name: 'Fastenal Company', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'PAYX', name: 'Paychex Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'VRSK', name: 'Verisk Analytics', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'RSG', name: 'Republic Services', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DAL', name: 'Delta Air Lines', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'LUV', name: 'Southwest Airlines', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'UAL', name: 'United Airlines', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  
  // Communication Services
  { symbol: 'NFLX', name: 'Netflix Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'DIS', name: 'Walt Disney Co.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'T', name: 'AT&T Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'VZ', name: 'Verizon Communications', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'TMUS', name: 'T-Mobile US', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CHTR', name: 'Charter Communications', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'EA', name: 'Electronic Arts', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'OMC', name: 'Omnicom Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'IPG', name: 'Interpublic Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MTCH', name: 'Match Group', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'LYV', name: 'Live Nation Entertainment', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PARA', name: 'Paramount Global', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'FOXA', name: 'Fox Corporation Class A', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'NWS', name: 'News Corp Class B', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  
  // Energy
  { symbol: 'XOM', name: 'Exxon Mobil Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CVX', name: 'Chevron Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'COP', name: 'ConocoPhillips', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SLB', name: 'Schlumberger Limited', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EOG', name: 'EOG Resources', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MPC', name: 'Marathon Petroleum', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PSX', name: 'Phillips 66', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'VLO', name: 'Valero Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'OXY', name: 'Occidental Petroleum', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'WMB', name: 'Williams Companies', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'KMI', name: 'Kinder Morgan', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HES', name: 'Hess Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DVN', name: 'Devon Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HAL', name: 'Halliburton Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BKR', name: 'Baker Hughes', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'OKE', name: 'ONEOK Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'FANG', name: 'Diamondback Energy', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'TRGP', name: 'Targa Resources', exchange: 'NYSE', currency: 'USD', region: 'US' },
  
  // Utilities
  { symbol: 'NEE', name: 'NextEra Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DUK', name: 'Duke Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SO', name: 'Southern Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'D', name: 'Dominion Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AEP', name: 'American Electric Power', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'SRE', name: 'Sempra Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EXC', name: 'Exelon Corporation', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'XEL', name: 'Xcel Energy', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'ED', name: 'Consolidated Edison', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PCG', name: 'PG&E Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'WEC', name: 'WEC Energy Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ES', name: 'Eversource Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AWK', name: 'American Water Works', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DTE', name: 'DTE Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EIX', name: 'Edison International', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PPL', name: 'PPL Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'FE', name: 'FirstEnergy Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ETR', name: 'Entergy Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AEE', name: 'Ameren Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CMS', name: 'CMS Energy', exchange: 'NYSE', currency: 'USD', region: 'US' },
  
  // Materials
  { symbol: 'LIN', name: 'Linde plc', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'APD', name: 'Air Products and Chemicals', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SHW', name: 'Sherwin-Williams', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ECL', name: 'Ecolab Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'NEM', name: 'Newmont Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CTVA', name: 'Corteva Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DOW', name: 'Dow Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DD', name: 'DuPont de Nemours', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PPG', name: 'PPG Industries', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'NUE', name: 'Nucor Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'VMC', name: 'Vulcan Materials', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MLM', name: 'Martin Marietta Materials', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ALB', name: 'Albemarle Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'IFF', name: 'International Flavors & Fragrances', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'LYB', name: 'LyondellBasell Industries', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CF', name: 'CF Industries Holdings', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MOS', name: 'Mosaic Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'FMC', name: 'FMC Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'STLD', name: 'Steel Dynamics', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'PKG', name: 'Packaging Corp of America', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'IP', name: 'International Paper', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'WRK', name: 'WestRock Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AVY', name: 'Avery Dennison', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SEE', name: 'Sealed Air Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CE', name: 'Celanese Corporation', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EMN', name: 'Eastman Chemical', exchange: 'NYSE', currency: 'USD', region: 'US' },
  
  // Real Estate
  { symbol: 'AMT', name: 'American Tower Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PLD', name: 'Prologis Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'CCI', name: 'Crown Castle Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EQIX', name: 'Equinix Inc.', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'SPG', name: 'Simon Property Group', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PSA', name: 'Public Storage', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'O', name: 'Realty Income Corp.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'WELL', name: 'Welltower Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'DLR', name: 'Digital Realty Trust', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'VICI', name: 'VICI Properties', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'AVB', name: 'AvalonBay Communities', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EQR', name: 'Equity Residential', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ARE', name: 'Alexandria Real Estate', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'VTR', name: 'Ventas Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'EXR', name: 'Extra Space Storage', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'SBAC', name: 'SBA Communications', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'WY', name: 'Weyerhaeuser Company', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'MAA', name: 'Mid-America Apartment', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'IRM', name: 'Iron Mountain', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'UDR', name: 'UDR Inc.', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'HST', name: 'Host Hotels & Resorts', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'KIM', name: 'Kimco Realty', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'REG', name: 'Regency Centers', exchange: 'NASDAQ', currency: 'USD', region: 'US' },
  { symbol: 'CPT', name: 'Camden Property Trust', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'ESS', name: 'Essex Property Trust', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'BXP', name: 'Boston Properties', exchange: 'NYSE', currency: 'USD', region: 'US' },
  { symbol: 'PEAK', name: 'Healthpeak Properties', exchange: 'NYSE', currency: 'USD', region: 'US' },
];

// Major European equities (ADRs trading on US exchanges)
export const EU_SYMBOLS: SymbolInfo[] = [
  // Technology
  { symbol: 'ASML', name: 'ASML Holding N.V.', exchange: 'NASDAQ', currency: 'USD', region: 'EU' },
  { symbol: 'SAP', name: 'SAP SE', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'SHOP', name: 'Shopify Inc.', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'SPOT', name: 'Spotify Technology', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'ARM', name: 'ARM Holdings', exchange: 'NASDAQ', currency: 'USD', region: 'EU' },
  
  // Healthcare
  { symbol: 'NVS', name: 'Novartis AG', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'AZN', name: 'AstraZeneca PLC', exchange: 'NASDAQ', currency: 'USD', region: 'EU' },
  { symbol: 'NVO', name: 'Novo Nordisk A/S', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'GSK', name: 'GSK plc', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'SNY', name: 'Sanofi', exchange: 'NASDAQ', currency: 'USD', region: 'EU' },
  
  // Consumer & Retail
  { symbol: 'UL', name: 'Unilever PLC', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'DEO', name: 'Diageo plc', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'NSRGY', name: 'Nestle S.A.', exchange: 'OTC', currency: 'USD', region: 'EU' },
  { symbol: 'BUD', name: 'Anheuser-Busch InBev', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  
  // Energy
  { symbol: 'SHEL', name: 'Shell PLC', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'BP', name: 'BP plc', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'TTE', name: 'TotalEnergies SE', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'EQNR', name: 'Equinor ASA', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  
  // Financial Services
  { symbol: 'HSBC', name: 'HSBC Holdings', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'UBS', name: 'UBS Group AG', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'CS', name: 'Credit Suisse Group', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'BCS', name: 'Barclays PLC', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'ING', name: 'ING Groep N.V.', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'DB', name: 'Deutsche Bank AG', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  
  // Industrials
  { symbol: 'ABB', name: 'ABB Ltd', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'RELX', name: 'RELX PLC', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'RHHBY', name: 'Roche Holding AG', exchange: 'OTC', currency: 'USD', region: 'EU' },
  { symbol: 'RIO', name: 'Rio Tinto Group', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'VALE', name: 'Vale S.A.', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'MT', name: 'ArcelorMittal', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  
  // Telecom
  { symbol: 'VOD', name: 'Vodafone Group', exchange: 'NASDAQ', currency: 'USD', region: 'EU' },
  { symbol: 'ORAN', name: 'Orange S.A.', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'NOK', name: 'Nokia Corporation', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'ERIC', name: 'Ericsson', exchange: 'NASDAQ', currency: 'USD', region: 'EU' },
  
  // Luxury & Fashion
  { symbol: 'LVMUY', name: 'LVMH Moet Hennessy', exchange: 'OTC', currency: 'USD', region: 'EU' },
  { symbol: 'PPRUY', name: 'Kering S.A.', exchange: 'OTC', currency: 'USD', region: 'EU' },
  
  // Automotive
  { symbol: 'TM', name: 'Toyota Motor Corp.', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'HMC', name: 'Honda Motor Co.', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'RACE', name: 'Ferrari N.V.', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'STLA', name: 'Stellantis N.V.', exchange: 'NYSE', currency: 'USD', region: 'EU' },
  { symbol: 'VWAGY', name: 'Volkswagen AG', exchange: 'OTC', currency: 'USD', region: 'EU' },
  { symbol: 'BMWYY', name: 'BMW AG', exchange: 'OTC', currency: 'USD', region: 'EU' },
  { symbol: 'MBGYY', name: 'Mercedes-Benz Group', exchange: 'OTC', currency: 'USD', region: 'EU' },
];

export const ALL_SYMBOLS = [...US_SYMBOLS, ...EU_SYMBOLS];

export function getSymbolInfo(symbol: string): SymbolInfo | undefined {
  return ALL_SYMBOLS.find(s => s.symbol.toUpperCase() === symbol.toUpperCase());
}

// Get symbols by sector for efficient batching
export function getSymbolsByRegion(region: 'US' | 'EU'): SymbolInfo[] {
  return region === 'US' ? US_SYMBOLS : EU_SYMBOLS;
}
